name: Ozone Build
on: push
jobs:
  build:
    name: Compile
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          env:
            TEST_TYPE: build
  unit:
    name: Unit test
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          env:
            TEST_TYPE: unit
        - uses: actions/upload-artifact@master
          if: always()
          with:
             name: results
             path: target/unit

  integration:
    name: Integration tests
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          env:
            TEST_TYPE: integration
        - uses: actions/upload-artifact@master
          if: always()
          with:
             name: results
             path: target/integration
  rat:
    name: Licence check
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          env:
            TEST_TYPE: rat
        - uses: actions/upload-artifact@master
          if: always()
          with:
             name: results
             path: target/rat

  author:
    name: Author tag usage check
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          env:
            TEST_TYPE: author
        - uses: actions/upload-artifact@master
          if: always()
          with:
             name: results
             path: target/author

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          env:
            TEST_TYPE: checkstyle
        - uses: actions/upload-artifact@master
          if: always()
          with:
             name: result
             path: target/checkstyle
  findbugs:
    name: Findbugs
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          env:
            TEST_TYPE: findbugs
        - uses: actions/upload-artifact@master
          if: always()
          with:
             name: results
             path: target/findbugs
  acceptance:
    name: Acceptance
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - uses: ./.github/actions/build
          env:
            TEST_TYPE: acceptance
        - uses: actions/upload-artifact@master
          if: always()
          with:
             name: results
             path: target/acceptance

