name: Automatic rebase
on:
   schedule:
       - cron: '*/2 * * * *'
jobs:
  build:
    name: Rebase
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
        - run: ./.github/workflows/rebase.sh 
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

