name: testMultiBlockWrites3
on:
  schedule:
   - cron: '0 0,12 * * *'
jobs:
  it-client:
    name: it-client
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master
          with:
            ref: master-test
        - uses: ./.github/buildenv
          with:
             args: ./hadoop-ozone/dev-support/checks/integration.sh -Dtest=TestCloseContainerHandlingByClient
        - uses: actions/upload-artifact@master
          if: always()
          with:
            name: it-client
            path: target/integration
